name: Sync

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH signing key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SIGNING_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          git config --global gpg.format ssh
          git config --global user.signingKey ~/.ssh/id_ed25519
          git config --global user.name "Lemuel DLS"
          git config --global user.email "26912197+lemueldls@users.noreply.github.com"

      - name: Sync upstream
        run: |
          git remote add upstream git@github.com:caelestia-dots/shell.git
          git pull upstream main
          git add -A
          git commit -S -m "chore: sync upstream" || echo "No changes to commit"
          git push
